### ISSUE TITLE
Inquiry about Paper Link

### ISSUE THREAD

**Issue by debuleilei** [SebastianJanampa/SOFI#1]
@SebastianJanampa hello,  I hope this message finds you well. I  found it fascinating. I’m very interested in reading the paper related to it. If possible, could you please share the link to the paper?

Thank you for your time and for your contributions to the field!

**Comment by SebastianJanampa** [comment]
Hello. I appreciate your interest and am sorry for the late reply. Here's the link for our paper: https://arxiv.org/abs/2409.15553
